---
# ARK Node Dashboard Widgets Configuration

- logo:
    icon: https://tailscale.com/favicon.ico

- greeting:
    text_size: 4xl
    text: "ARK Node Command Center"

- systemload:
    label: CPU
    cpu: true

- memory:
    label: RAM

- resources:
    backend: docker
    expanded: true
    cpu: true
    memory: true
    disk:
      - /
      - /mnt/dock

- search:
    provider: duckduckgo
    target: _blank
    showSearchSuggestions: true

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: false
